#!/usr/bin/env python3
"""Experiment 323: cross-family Q4 leave-one-residue-out comparison.

Compare two families on the exact same physically observed Q4 residues:

1. tail-index-only:
   each A-I class has exactly one slash among its three Q4 depths;
   no primary POS3, recursion, route, terminal, or machine state is used.

2. incumbent:
   reuse the frozen leave-one-residue-out results already generated by
   scripts/audit_sticker_prediction_holdouts.py.

The comparison is coverage-aware: count forced predictions, ambiguous
predictions that include the truth, and exclusions. It does not score
unpredicted primary cells against the tail-only family.
"""

from __future__ import annotations

import csv
import os
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OBS = ROOT / os.environ.get("GRA_EDISNI_OBSERVATIONS_FILE", "data/observations.csv")
INCUMBENT = ROOT / "data" / "sticker-holdout-residue-results.csv"
SERIAL_ORDER = "ABCDEFGHI"


def load_rows():
    with OBS.open(newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def actual_by_residue(rows):
    out = defaultdict(set)
    for row in rows:
        out[int(row["residue"])].add(row["symbol"])
    assert all(len(v) == 1 for v in out.values())
    return {r: next(iter(v)) for r, v in out.items()}


def slash_positions(rows, j):
    allowed = set(range(3))
    for row in rows:
        residue = int(row["residue"])
        if residue < 82:
            continue
        offset = residue - 82
        depth = offset // 9
        jj = offset % 9
        if jj != j:
            continue
        symbol = row["symbol"]
        if symbol == "/":
            allowed.intersection_update({depth})
        elif symbol == ".":
            allowed.discard(depth)
        else:
            raise AssertionError(symbol)
    return allowed


def classify(predicted, actual):
    if len(predicted) == 1:
        return "forced-correct" if actual in predicted else "forced-wrong"
    return "ambiguous-includes-actual" if actual in predicted else "ambiguous-excludes-actual"


def tail_only_holdouts(rows):
    actual = actual_by_residue(rows)
    q4_residues = sorted(r for r in actual if r >= 82)
    results = []
    for residue in q4_residues:
        reduced = [row for row in rows if int(row["residue"]) != residue]
        offset = residue - 82
        depth = offset // 9
        j = offset % 9
        candidates = slash_positions(reduced, j)
        predicted = {"/" if slash_depth == depth else "." for slash_depth in candidates}
        results.append({
            "residue": residue,
            "background": SERIAL_ORDER[j],
            "actual": actual[residue],
            "candidate_slash_positions": "".join(map(str, sorted(candidates))),
            "predicted_symbols": "".join(sorted(predicted)),
            "status": classify(predicted, actual[residue]),
        })
    return results


def incumbent_holdouts():
    out = {}
    with INCUMBENT.open(newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            residue = int(row["residue"])
            if residue >= 82:
                out[residue] = row
    return out


def main():
    rows = load_rows()
    tail = tail_only_holdouts(rows)
    incumbent = incumbent_holdouts()

    residues = [r["residue"] for r in tail]
    assert residues == [85, 86, 89, 90, 92, 95, 96, 97, 98, 101, 108]
    assert set(residues) == set(incumbent)

    tail_counts = Counter(r["status"] for r in tail)
    incumbent_counts = Counter(incumbent[r]["status"] for r in residues)

    assert tail_counts == Counter({
        "ambiguous-includes-actual": 8,
        "forced-correct": 3,
    })
    assert incumbent_counts == Counter({
        "forced-correct": 10,
        "ambiguous-includes-actual": 1,
    })

    assert not tail_counts["forced-wrong"]
    assert not tail_counts["ambiguous-excludes-actual"]
    assert not incumbent_counts["forced-wrong"]
    assert not incumbent_counts["ambiguous-excludes-actual"]

    print("Experiment 323")
    print("shared Q4 holdout residues:", len(residues))
    print("tail-index-only:", dict(tail_counts))
    print("incumbent:", dict(incumbent_counts))
    print("tail forced coverage: 3/11")
    print("incumbent forced coverage: 10/11")
    print("RESULT: neither family excludes any withheld true Q4 symbol")
    print("RESULT: the incumbent is more constraining on the shared Q4 domain")
    print("RESULT: row/chunk versus column/rail semantics do not alter tail-cell predictions")
    for row in tail:
        r = row["residue"]
        print(
            f"r{r} {row['background']} actual={row['actual']} "
            f"tail={row['predicted_symbols']}({row['status']}) "
            f"incumbent={incumbent[r]['predicted_symbols']}({incumbent[r]['status']})"
        )


if __name__ == "__main__":
    main()
