#!/usr/bin/env python3
"""Experiment 270: physical-simplicity audit of the Q4 polarity gauge.

Experiment 260 factorized the 16 recursively closed Q4 polarity words into:
  * an 8-word 14-state/100 gauge cube generated by A, C, and F+I flips;
  * the same cube with D toggled, yielding the 12-state/110 sibling.

This experiment deliberately ignores terminal payload and state count when
ranking those 16 words. It asks whether the authored all-slash polarity word is
selected by simple physical regularity on the actual 3x3 artwork.

Predeclared locality measures:
  1. polarity Hamming weight: number of dot-exception stacks;
  2. orthogonal domain walls on the physical 3x3 artwork;
  3. number of mixed physical rows;
  4. number of mixed physical columns.

These measures use only the polarity assignment and artwork geometry. They do
not inspect selector depths, recursion outputs, terminal values, or hidden
states.
"""

from __future__ import annotations

from itertools import product

from audit_q4_polarity_gauge import (
    A,
    C,
    D,
    FI,
    SERIAL_ORDER,
    label,
    xor_span,
)

PHYSICAL_LAYOUT = (
    ("I", "A", "B"),
    ("C", "D", "E"),
    ("F", "G", "H"),
)


def bit(mask: int, letter: str) -> int:
    return int(bool(mask & (1 << SERIAL_ORDER.index(letter))))


def domain_walls(mask: int) -> int:
    walls = 0
    for row in range(3):
        for col in range(3):
            here = PHYSICAL_LAYOUT[row][col]
            if row + 1 < 3:
                walls += bit(mask, here) != bit(mask, PHYSICAL_LAYOUT[row + 1][col])
            if col + 1 < 3:
                walls += bit(mask, here) != bit(mask, PHYSICAL_LAYOUT[row][col + 1])
    return walls


def mixed_rows(mask: int) -> int:
    return sum(
        len({bit(mask, letter) for letter in row}) > 1
        for row in PHYSICAL_LAYOUT
    )


def mixed_columns(mask: int) -> int:
    return sum(
        len({bit(mask, PHYSICAL_LAYOUT[row][col]) for row in range(3)}) > 1
        for col in range(3)
    )


def metrics(mask: int) -> tuple[int, int, int, int]:
    return (
        mask.bit_count(),
        domain_walls(mask),
        mixed_rows(mask),
        mixed_columns(mask),
    )


def main() -> None:
    maximal = xor_span((A, C, FI))
    sibling = {mask ^ D for mask in maximal}
    closure = maximal | sibling

    assert len(maximal) == 8
    assert len(sibling) == 8
    assert len(closure) == 16

    scored = {mask: metrics(mask) for mask in closure}

    # The authored all-slash word is the zero mask. It is the only closure word
    # that is globally homogeneous, so all four independent locality costs hit
    # their absolute lower bound simultaneously only there.
    assert scored[0] == (0, 0, 0, 0)
    assert all(scored[mask] != (0, 0, 0, 0) for mask in closure if mask)

    axis_winners = []
    for axis in range(4):
        best = min(score[axis] for score in scored.values())
        winners = {mask for mask, score in scored.items() if score[axis] == best}
        assert best == 0
        axis_winners.append(winners)

    # Hamming weight, domain walls, and mixed rows uniquely prefer zero.
    # Mixed columns alone has one expected tie: C+F+I flips the complete
    # left physical column I/C/F, leaving every column internally homogeneous.
    assert axis_winners[:3] == [{0}, {0}, {0}]
    assert axis_winners[3] == {0, C | FI}

    # Even if the four costs are collapsed to a simple unweighted sum, the
    # unique minimum remains the authored all-slash polarity.
    total = {
        mask: sum(score)
        for mask, score in scored.items()
    }
    best_total = min(total.values())
    assert best_total == 0
    assert {mask for mask, value in total.items() if value == best_total} == {0}

    print("Experiment 270")
    print("mask | class | flipped stacks | walls | mixed rows | mixed cols")
    for mask in sorted(closure):
        family = "14-state" if mask in maximal else "12-state"
        weight, walls, rows, cols = scored[mask]
        print(
            f"{label(mask):>9} | {family:>8} | "
            f"{weight:>14} | {walls:>5} | {rows:>10} | {cols:>10}"
        )

    print("RESULT: all-slash uniquely minimizes flips, domain walls, and mixed rows")
    print("RESULT: mixed columns alone ties all-slash with C+F+I, the full left-column flip")
    print("RESULT: all-slash is the unique simultaneous four-metric zero and unique minimum total cost")
    print("RESULT: physical homogeneity selects the zero gauge origin without using terminal output")
    print("RESULT: the same criterion also rejects the D-flipped 12-state sibling")
    print("CAUTION: physical simplicity is a compact authoring prior, not a new sticker observation")


if __name__ == "__main__":
    main()
